# Generated by Django 5.1.5 on 2025-03-26 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_loanrequest_approved_date_loanrequest_next_due_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrequest',
            name='last_payment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
